In [1]:
### LESSON 3: NumpPy and Pandas for 2D Data ###

In [2]:
# Questions to answer using New York Subway Data:
#     1. How does temperature affect ridership?
#     2. How rain during the morning commute hours (8-10am) affect the number of commuters?
#     3. At what point does the weather really make a difference? Is there a temp or an amount of rainfall at
#       which we can expect ridership to increase or decrease?
#     4. What hours have the most riders? Least riders?
#     5. What stations are busiest? Slowest?

In [3]:
import numpy as np

In [16]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])


In [7]:
# Accessing elements (row, column)
print ridership[1, 3]
# 2328
print ridership[1:3, 3:5]
# [2328, 2539],
# [6461, 2691]
print ridership[1, :]
# [1478, 3877, 3674, 2328, 2539]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [10]:
# Vectorized operations on rows or columns
print ridership[0, :] + ridership[1, :]
# [1478 3877 3676 2333 2539]
print ridership[:, 0] + ridership[:, 1]
# [0 5355 5701 4952 6430 5509 324 2 5223 5385]

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [11]:
# Vectorized operations on entire arrays
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[1,1,1], [2,2,2], [3,3,3]])

print a + b
# [2,3,4], [6,7,8], [10,11,12]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [27]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    max_ridership_loc = ridership[0, :].argmax()
    overall_mean = ridership.mean()
    mean_for_max = ridership[:, max_ridership_loc].mean()
    
    return (overall_mean, mean_for_max)

In [28]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

In [29]:
# Axis argument... axis=0, means calculate down the column;` axis=1, means calculate across the row

In [31]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print a.sum()
print a.sum(axis=0)
print a.sum(axis=1)

45
[12 15 18]
[ 6 15 24]


In [33]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [36]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    mean_riderships = ridership.mean(axis=0)
    print mean_riderships
    max_daily_ridership = mean_riderships.max()
    min_daily_ridership = mean_riderships.min()
    
    return (max_daily_ridership, min_daily_ridership)

In [37]:
min_and_max_riders_per_day(ridership)

[ 1071.2  2814.9  2718.8  3239.9  1868.2]


(3239.9000000000001, 1071.2)

In [38]:
# Accessing elements:
# use .loc, .iloc to find within the dataframe. if you use .values it will return a 2D NumPy array.

In [39]:
import pandas as pd

In [40]:
# Create the data frame:
# data as a 2D array, index gives row names, by date for this frame, columns gives names to each ridership station.

ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [42]:
ridership_df
# ooo pretty 😍

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [44]:
# DataFrame creation

# create out of a dict mapping column names to values
df_1 = pd.DataFrame({'A': [0,1,2], 'B': [3,4,5]})
print df_1

#create using a list of lists of a NumPy 2D array
df_2 = pd.DataFrame([[0,1,2], [3,4,5]], columns=['A','B','C'])
print df_2

# note that the rows are automatically given numbers (0,1,2, etc)

   A  B
0  0  3
1  1  4
2  2  5
   A  B  C
0  0  1  2
1  3  4  5


In [59]:
# Accessing elements

# use .iloc when locating by the given pandas index
print ridership_df.iloc[0]

print ridership_df.iloc[1,3]
# 2328  --- row first, then column (like alg x, y)

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
2328


In [51]:
# use .loc to locate by row name
print ridership_df.loc['05-05-11']

R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64


In [52]:
# use normal indexing brackets to locate columns by name
print ridership_df['R003']

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64


In [61]:
# Access multiple rows (.iloc to access by row)

print ridership_df.iloc[1:4]

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [63]:
# Access multiple columns (using usual indexing brackets)

print ridership_df[['R003','R005']]

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [70]:
# Using Pandas axis

df = pd.DataFrame({'A': [0,1,2], 'B': [3,4,5]})
print df
print df.sum()
# sums each element (A, B)
print df.sum(axis=1)
# sums rows (0+3, 1+4, 2+5)
print df.values.sum()
# return a Numpy 2D array and sum all the elements= 15

   A  B
0  0  3
1  1  4
2  2  5
A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [86]:
def mean_riders_for_max_station_df(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    max_day = ridership.iloc[0].argmax()
    overall_mean = ridership.values.mean()
    mean_for_max = ridership[max_day].mean()
    
    return (overall_mean, mean_for_max)

In [87]:
mean_riders_for_max_station_df(ridership_df)

(2342.5999999999999, 3239.9)

In [88]:
# taking means:
# if you take ridership.mean(), it returns means for each individual row
# adding ridership.values.mean() will return the mean for the entire data set

In [89]:
# DataFrames are a great data structure to represent CSV's: 
# They provide a separate data type to each column

# read_csv = built in function that reads CSV's into Pandas DFs

In [91]:
subway_df = pd.read_csv('./nyc_subway_weather.csv')

In [92]:
subway_df.head()
# prints first 5 rows of the DF as a sampling of the info

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [94]:
subway_df.describe()
# gives some stats about the df as a whole

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog      ...          pressurei          rain         tempi  \
count  42649.000000      ...       42649.000000  42649.000000  42649.000000   
mean       0.009824      ...          29.971096      0.224741     63.103780   
std        0.098631      ...           0.137942      0.417417      8.455597   
min        0.000000      ...          29.550000      0.000000     46.900000   
25%        0.000000      ...          29.890000      0.000000     57.000000   
50%        0.000000      ...          29.960000      0.000000     61.000000   
75%        0.000000      ...          30.060000      0.000000     69.100000   
max        1.000000      ...          30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

In [95]:
# Correlation Coefficient: Pearson's r

In [215]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: meanprecipi, dtype: float64


In [237]:
def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    x_standard = (x - x.mean()) / x.std(ddof=0)
    y_standard = (y - y.mean()) / y.std(ddof=0)
    
    xy_standard_units = x_standard * y_standard
    correlation = xy_standard_units.mean()
    
    return correlation

In [239]:
print correlation(entries, rain)

0.0356485157722


In [240]:
print correlation(entries, temp)

-0.0266933483216


In [241]:
print correlation(rain, temp)

-0.229034323408


In [242]:
print correlation(entries, cum_entries)

0.585895470766


In [ ]:
# Pandas Axis Names